---
title: "Homework 5"
output: github_document
date: "2022-11-16"
---

```{r, message = FALSE}
library(tidyverse)
library(stringr)
library(ggplot2)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

# Problem 2
```{r, message = FALSE}
p2 = read_csv(file = "./data/homicide-data.csv") %>% 
     janitor::clean_names()
```
## Describe the raw dataset. 
This data set is about criminal homicides over the past decade in 50 of the largest American cities. This data set has `r ncol(p2)` variables and `r nrow(p2)` observations. It includes variables: `r ls(p2)`.

## Data Manipulation
```{r, message = FALSE}
a = p2 %>% 
  mutate(city_state = str_c(city, "_", state)) %>%
  group_by(city_state) %>% 
  summarise(total_homicides = n())

b = p2 %>% 
  mutate(city_state = str_c(city, "_", state)) %>% 
  filter(disposition != "Closed by arrest") %>% 
  group_by(city_state) %>% 
  summarise(unsolved = n())

new = full_join(a, b, by = "city_state") %>% 
  filter(city_state !=	"Tulsa_AL")

p_test = function(x,n){
  prop.test(x,n) %>% 
  broom::tidy() %>% 
  select(estimate, starts_with("conf"))
}
```
kb3246

## MD estimates
```{r}
p_test(
  new %>% 
  filter(city_state %in% "Baltimore_MD") %>% 
  pull(unsolved),
  new %>% 
  filter(city_state %in% "Baltimore_MD") %>% 
  pull(total_homicides)
)
```


## All city 
```{r}
final = 
  new %>% 
  mutate(summary = map2(.x = new %>% pull(unsolved), 
             .y = new %>% pull(total_homicides), 
             ~p_test(x = .x, n = .y))) %>% 
  unnest()
```

## Plot
```{r}
final %>%
  arrange(desc(estimate)) %>% 
  ggplot(aes(x = fct_inorder(city_state), y = estimate)) + 
  geom_bar(stat='identity') + geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) + theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) 
```



